name: "Enforce PR Title Format"

on:
  workflow_call:
  pull_request:
    branches:
      - 'develop'
      - 'release/*'

permissions:
  pull-requests: read
  contents: read

jobs:
  PR-Title-Check:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR author and CODEOWNERS file (no token)
        id: prmeta
        run: |
          echo "::set-output name=is_bot::false"
          echo "::set-output name=has_codeowners::false"
        shell: bash

      - name: Skip for bot PRs
        if: ${{ steps.prmeta.outputs.is_bot == 'true' }}
        run: echo "Skipping title check, PR opened by bot user (ci-builder, renovate, or bot)."

      - name: Skip if CODEOWNERS file changed
        if: ${{ steps.prmeta.outputs.has_codeowners == 'true' }}
        run: echo "Skipping PR Title check as CODEOWNERS file was changed."

      - name: Enforce PR Title Format
        if: ${{ steps.prmeta.outputs.is_bot != 'true' && steps.prmeta.outputs.has_codeowners != 'true' }}
        run: |
          echo "This is where you would enforce the PR title format."
        shell: bash
