name: "Enforce PR Title Format"

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:

      - name: Check if only CODEOWNERS file was changed
        id: codeowners
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed("Not a PR event.");

            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });

            const onlyCodeowners = files.length === 1 && files[0].filename === 'CODEOWNERS';
            core.setOutput("only_codeowners", onlyCodeowners);

      - name: Check if PR author is an automation bot (ci-builder/renovate)
        id: autobot
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed("Not a PR event.");

            const botAuthors = ['ci-builder', 'renovate[bot]', 'renovate'];
            const isBot = botAuthors.includes(pr.user.login);
            core.setOutput("is_bot", isBot);

      - name: Enforce PR title format
        if: steps.codeowners.outputs.only_codeowners != 'true' && steps.autobot.outputs.is_bot != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed("Not a PR event.");

            const titleRegex = /^CCL-\d{5}\s.+/;
            if (!titleRegex.test(pr.title)) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: pr.number,
                body: "❌ PR title must start with `CCL-<5digit> <description>` (e.g. `CCL-12345 Add feature`)."
              });
              core.setFailed("PR title does not match the required format.");
            }

      - name: Skip title check for CODEOWNERS-only PRs
        if: steps.codeowners.outputs.only_codeowners == 'true'
        run: echo "✅ Skipping title check: only CODEOWNERS file changed."

      - name: Skip title check for bot PRs
        if: steps.autobot.outputs.is_bot == 'true'
        run: echo "✅ Skipping title check: PR opened by bot user (ci-builder or renovate)."
