name: "Enforce PR Title Format"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_call:

permissions:
  pull-requests: read
  contents: read

jobs:
  PR-Title-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files in PR
        id: changed-files
        uses: actions/github-script@v3
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed("Not a PR event.");
            const files = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            const fileNames = files.data.map(file => file.filename);
            core.setOutput("file_names", JSON.stringify(fileNames));

      - name: Check if only CODEOWNERS file was changed
        id: codeowners
        run: |
          file_names=$(echo "${{ steps.changed-files.outputs.file_names }}" | jq -r '.[]')
          only_codeowners="true"
          for file in $file_names; do
            if [ "$file" != "CODEOWNERS" ] && [ "$file" != ".github/CODEOWNERS" ]; then
              only_codeowners="false"
              break
            fi
          done
          echo "only_codeowners=$only_codeowners" >> $GITHUB_OUTPUT

      - name: Check if PR author is a bot (ci-builder/renovate)
        id: autobot
        uses: actions/github-script@v3
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed("Not a PR event.");
            const botAuthors = ['ci-builder', 'renovate[bot]', 'renovate'];
            core.setOutput("is_bot", botAuthors.includes(pr.user.login));

      - name: Skip check for CODEOWNERS-only PRs
        if: steps.codeowners.outputs.only_codeowners == 'true'
        run: echo "Skipping PR Title check as only CODEOWNERS file was changed."

      - name: Skip for bot PRs
        if: steps.autobot.outputs.is_bot == 'true'
        run: echo "Skipping title check, PR opened by bot user (ci-builder or renovate)."

      - name: Enforce PR Title Format
        if: steps.codeowners.outputs.only_codeowners != 'true' && steps.autobot.outputs.is_bot != 'true'
        uses: actions/github-script@v3
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed("Not a PR event.");
            const pattern = /^CCL-\d{5}\s.+/;
            if (!pattern.test(pr.title)) {
              core.setFailed("PR title must start with CCL-<5digit> <description> (eg. 'CCL-12345 Add feature').");
            }
