name: "Enforce PR Title Pattern for Jira Ticket"

on:
  workflow_call:

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if only CODEOWNERS file changed
        id: codeowners-only
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.payload.pull_request.number;
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number,
                per_page: 100
              }
            );
            const changedFiles = files.map(f => f.filename);
            if (changedFiles.length === 1 && changedFiles[0] === 'CODEOWNERS') {
              core.setOutput("only_codeowners", "true");
            } else {
              core.setOutput("only_codeowners", "false");
            }

      - name: Validate PR Title Pattern
        if: steps.codeowners-only.outputs.only_codeowners == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const jiraPattern = /^CCL-\d+\s.+/; // Adjust 'CCL' to your Jira prefix if needed
            if (!jiraPattern.test(prTitle)) {
              const body = "❌ **PR title must match `CCL-<number> <description>` (e.g. `CCL-12345 Add feature`).**\n\nPlease update the title to reference an active Jira ticket.";
              await github.issues.createComment({
                ...context.repo,
                issue_number: context.payload.pull_request.number,
                body
              });
              core.setFailed("PR title does not match required Jira pattern.");
            }

      - name: Skip check for CODEOWNERS-only PRs
        if: steps.codeowners-only.outputs.only_codeowners == 'true'
        run: echo "Skipping PR title check for CODEOWNERS-only PR."
