name: "Enforce PR Title Format"

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if only CODEOWNERS changed
        id: codeowners
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed("Not a PR event.");
            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            core.setOutput("only_codeowners", files.length === 1 && files[0].filename === 'CODEOWNERS');

      - name: Enforce PR title format
        if: steps.codeowners.outputs.only_codeowners != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed("Not a PR event.");
            if (!/^CCL-\d{5}\s.+/.test(pr.title)) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: pr.number,
                body: "❌ PR title must follow jira ticket followed by description: `CCL-<5digitnumber> <description>` (e.g. `CCL-12345 Add feature`)."
              });
              core.setFailed("PR title does not match format.");
            }

      - name: Skip for CODEOWNERS-only PRs
        if: steps.codeowners.outputs.only_codeowners == 'true'
        run: echo "Skipping title check for CODEOWNERS-only PR."
