name: "Enforce PR Title Format"

on:
  workflow_call:
  pull_request:
    branches:
      - 'develop'
      - 'release/*'

jobs:
  PR-Title-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR metadata
        id: check_pr
        run: |
          # Check if PR author is a bot
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          if [[ "$PR_AUTHOR" =~ ^(ci-builder|renovate(\[bot\])?|bot)$ ]]; then
            echo "Skipping check: PR created by bot user ($PR_AUTHOR)"
            echo "is_bot=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "is_bot=false" >> $GITHUB_OUTPUT

          # Check for CODEOWNERS file changes
          CHANGED_FILES="${{ join(github.event.pull_request.changed_files, ' ') }}"
          if [[ "$CHANGED_FILES" =~ (^|[[:space:]])CODEOWNERS($|[[:space:]]) ]] || [[ "$CHANGED_FILES" =~ (^|[[:space:]])\.github/CODEOWNERS($|[[:space:]]) ]]; then
            echo "Skipping check: CODEOWNERS file modified"
            echo "has_codeowners=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "has_codeowners=false" >> $GITHUB_OUTPUT

      - name: Check PR title format
        if: steps.check_pr.outputs.is_bot != 'true' && steps.check_pr.outputs.has_codeowners != 'true'
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ ! "$PR_TITLE" =~ ^CCL-[0-9]{5}[[:space:]].+ ]]; then
            echo "Error: PR title must start with CCL-<5digit> followed by a description"
            echo "Example: CCL-12345 Add feature"
            echo "Your title: $PR_TITLE"
            exit 1
          fi
          echo "PR title format is valid: $PR_TITLE"
